CREATE PROCEDURE GuarantorSegmentCommercialProcedure()
BEGIN
    INSERT INTO gurantor_seg (
        Address_Line_1,
        Address_Line_2,
        Address_Line_3,
        Business_Category,
        Business_Industry_Type,
        CIN,
        City_Town,
        Country,
        Date_of_Birth,
        Date_of_Incorporation,
        DIN,
        District,
        Driving_Licence_ID,
        Fax_Area_Code,
        Fax_Number,
        Full_Name,
        Gender,
        Guarantor_DUNS_Number,
        Guarantor_Entity_Name,
        Guarantor_Type,
        Mobile_Number,
        PAN,
        Passport_Number,
        Pin_Code,
        Ration_Card_No,
        Service_Tax,
        State_Union_Territory,
        Telephone_Area_Code,
        Telephone_Number,
        TIN,
        UID,
        Voter_ID,
        Individual_Name_Prefix,
        cred_id
    )
    SELECT
        COALESCE(gs.Address_Line_1, ''),
        COALESCE(gs.Address_Line_2, ''),
        COALESCE(gs.Address_Line_3, ''),
        COALESCE(gs.Business_Category, ''),
        COALESCE(gs.Business___Industry_Type, ''),
        COALESCE(gs.CIN, ''),
        COALESCE(gs.City_Town, ''),
        COALESCE(gs.Country, ''),
        COALESCE(gs.Date_of_Birth, ''),
        COALESCE(gs.Date_of_Incorporation, ''),
        COALESCE(gs.DIN, ''),
        COALESCE(gs.District, ''),
        COALESCE(gs.Driving_Licence_ID, ''),
        COALESCE(gs.Fax_Area_Code, ''),
        COALESCE(gs.Fax_Number_s_, ''),
        COALESCE(gs.Full_Name, ''),
        IF(LENGTH(COALESCE(gs.Gender, '')) = 1,
           CONCAT('0', COALESCE(gs.Gender, '')),
           COALESCE(gs.Gender, '')
        ) AS Gender,
        COALESCE(gs.Guarantor_DUNS_Number, ''),
        COALESCE(gs.Guarantor_Entity_Name, ''),
        COALESCE(gs.Guarantor_Type, ''),
        COALESCE(gs.Mobile_Number_s_, ''),
        COALESCE(gs.PAN, ''),
        COALESCE(gs.Passport_Number, ''),
        COALESCE(gs.Pin_Code, ''),
        COALESCE(gs.Ration_Card_No, ''),
        COALESCE(gs.Service_Tax__, ''),
        COALESCE(gs.State_Union_Territory, ''),
        COALESCE(gs.Telephone_Area_Code, ''),
        COALESCE(gs.Telephone_Number_s_, ''),
        COALESCE(gs.TIN, ''),
        COALESCE(gs.UID, ''),
        COALESCE(gs.Voter_ID, ''),
        COALESCE(gs.Individual_Name_Prefix, ''),
        cf.cred_id
    FROM gs
    JOIN credit_facility_seg AS cf
      ON gs.A_c_No_ = cf.Account_Number
    WHERE cf.cred_id IS NOT NULL;
END;
