CREATE PROCEDURE `RelationshipSegCommercialProcedure`()
BEGIN
    INSERT INTO relationship_seg (
        borrower_id,
        Address_Line1,
        Address_Line2,
        Address_Line3,
        Business_Category,
        Business_entity_name,
        Business_Industry_Type,
        CIN,
        City_Town,
        CKYC,
        Company_Registration_Number,
        Country,
        Date_of_Birth,
        DIN,
        District,
        Driving_Licence_ID,
        Fax_Area_Code,
        Fax_Numbers,
        Full_Name,
        Gender,
        Mobile_Numbers,
        Individual_Name_prefix,
        PAN,
        Passport_Number,
        Percentage_of_Control,
        Pin_Code,
        Ration_Card_No,
        Related_Type,
        Relationship_DUNS_Number,
        Date_of_Incorporation,
        Service_Tax,
        State_union_territory,
        Telephone_Area_Code,
        Telephone_Numbers,
        TIN,
        Relationship,
        Udyam_Registration_Number,
        UID,
        Voter_Id
    )
    SELECT
        b.borrower_id,                                      -- first column
        COALESCE(c.Address_Line_1, ''),
        COALESCE(c.Address_Line_2, ''),
        COALESCE(c.Address_Line_3, ''),
        COALESCE(c.Business_Category, ''),
        COALESCE(c.Business_Entity_Name, ''),
        COALESCE(c.Business___Industry_Type, ''),
        COALESCE(c.CIN, ''),
        COALESCE(c.City_Town, ''),
        COALESCE(c.Other_ID, ''),                           -- CKYC
        COALESCE(c.Company_Registration_Number, ''),
        COALESCE(c.Country, ''),
        COALESCE(c.Date_of_Birth, ''),
        COALESCE(c.DIN, ''),
        COALESCE(c.District, ''),
        COALESCE(c.Driving_Licence_ID, ''),
        COALESCE(c.Fax_Area_Code, ''),
        COALESCE(c.Fax_Number_s_, ''),
        COALESCE(c.Full_Name, ''),
        IF(LENGTH(COALESCE(c.Gender, '')) = 1,
           CONCAT('0', COALESCE(c.Gender, '')),
           COALESCE(c.Gender, '')
        ) AS Gender,
        COALESCE(c.Mobile_Number_s_, ''),
        COALESCE(c.Individual_Name_Prefix, ''),
        COALESCE(c.PAN, ''),
        COALESCE(c.Passport_Number, ''),
        COALESCE(c.Percentage_of_Control, ''),
        COALESCE(c.Pin_Code, ''),
        COALESCE(c.Ration_Card_No, ''),
        COALESCE(c.Related_Type, ''),
        COALESCE(c.Relationship_DUNS_Number, ''),
        COALESCE(c.Date_of_Incorporation, ''),
        COALESCE(c.Service_Tax__, ''),
        COALESCE(c.State_Union_Territory, ''),
        COALESCE(c.Telephone_Area_Code, ''),
        COALESCE(c.Telephone_Number_s_, ''),
        COALESCE(c.TIN, ''),
        COALESCE(c.Relationship, ''),
        '',                                                 -- Udyam_Registration_Number placeholder
        COALESCE(c.UID, ''),
        COALESCE(c.Voter_ID, '')
    FROM Relationship_Segment c
    JOIN borrower_seg b
      ON c.A_c_No_ = SUBSTRING_INDEX(b.unique_commercial_id, '_', 1)
    WHERE b.borrower_id IS NOT NULL;

END